name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  #  pull_request:
  #    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # --------------------  Prepare folder to be zipped --------------------
  Check-TAGs:
    name: Prepare Folder
    runs-on: ubuntu-latest
    steps:
    - name: Check Tag
      if: !startsWith(github.ref, 'refs/tags/v')
      run: echo Needs a Tag to run
    - name: Check if has no TAG
      if: startsWith(github.ref, 'refs/tags/v')
  pack-zip:
    name: Prepare Folder
    runs-on: ubuntu-latest
    needs: Check-TAGs
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false    # without this checkout deletes empty folders after each use
          #{{ github.ref_name }}
      - run: mkdir AnexWeapons_zipFolder
      - uses: actions/upload-artifact@v2
        with:
          name: AnexWeapons_temp
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
            !.git
            !.github
            !.gradle
            !.idea
            !.run
            !build
            !libs
            !readme_resources
#      - name: List all upload-artifact folders only
#        run: ls -R
#      - name: check upload-artifact file log
#        run: |
#          cd
#          ls -R
# --------------------  copy server folder to working folder --------------------
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: actions/download-artifact@v3
        id: download_id
        with:
          name: AnexWeapons_temp
          path: "${{ github.workspace }}/AnexWeapons_zipFolder/Anex Weapons"               # ${{ github.workspace }}/Anexweapons-${{ github.ref_name }}
      - name: 'Echo download path'
        run: echo ${{steps.download_id.outputs.download-path}}
      - name: check download-artifact file log
        run: |
          cd
          ls -R
# --------------------  create zip file --------------------
      - uses: actions/checkout@v3
        with:
          clean: false
#      - name: Create Zip from Folders
#        uses: thedoctor0/zip-release@master
#        with:
#          type: 'zip'
#          filename: "Anexweapons_ppp"
#          path: ${{github.workspace}}/Anexweapons
#          directory: ${{github.workspace}}/Anexweapons
#          exclusions: '*data* *graphics* *jars* *sounds* *src* *.git* /*node_modules/* .editorconfig *.github* *.gradle* *.idea* *.run* /*build/* /*gradle/* /*libs /*readme_resources .gitattributes .gitignore build.gradle.kts gradle* gradle.* package.json package-lock.json README.md'
      - uses: papeloto/action-zip@v1
        with:
          files: AnexWeapons_zipFolder/
          dest: Anexweapons-${{ github.ref_name }}.zip
# generates list of all files in root directory, download log from actions tab in github to view
      - name: check thedoctor0 zip file log
        run: |
          cd
          ls -R
# --------------------  Upload zip to Github Release --------------------
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Realease to Github Releases
        uses: ncipollo/release-action@v1
        with:
          name: Anexweapons-${{ github.ref_name }}             # Release post Title Name
          artifacts: Anexweapons-${{ github.ref_name }}.zip         # Release File name
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: check ncipollo file log
        run: |
          cd
          ls -R
