# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
# Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# --------------------  create zip --------------------
  creating-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r testarchive.zip data
      - uses: actions/upload-artifact@v2
        with:
          name: testarchive.zip
          path: path/to/artifact/
# --------------------  download artifact to working directory --------------------
  download-zip:
    runs-on: ubuntu-latest
    needs: creating-zip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: testarchive.zip
          path: path/to/artifact/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact
# -- display path of download  --
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
# --------------------  upload built artifact --------------------
  upload-zip:
    runs-on: ubuntu-latest
    needs: download-zip
    steps:
      - uses: actions/upload-artifact@v3.0.0
        name: Upload a Build Artifact
        with:
          name: testarchive.zip
          path: path/to/artifact/ # or path/to/artifact