name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  #  pull_request:
  #    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # --------------------  Prepare folder to be zipped --------------------
  pack-zip:
    name: Prepare Folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir Anexweapons_02-${{ github.ref_name }}
      - uses: actions/upload-artifact@v2
        with:
          name: AnexWeapons_01
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
            !.git
            !.github
            !.gradle
            !.idea
            !.run
            !build
            !libs
            !readme_resources
      # -- display path of download  --
      #      - name: Echo download path
      #        run: |
      #          cd ${{ github.workspace }}
      #          ls -R
      - name: List all folders
        run: ls -R
      - name: check zip file log
        run: |
          cd
          ls -R
# --------------------  create zip file --------------------
      - uses: actions/checkout@v3
      - name: Copy out file from volume
        run: |
          sudo cp ${{ github.workspace }}/AnexWeapons_01/ /Anexweapons_02-${{ github.ref_name }}/
      - name: check zip file log
        run: |
          cd
          ls -R
# --------------------  create zip file --------------------
      - uses: actions/checkout@v3
      - name: Create Zip from Folders
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'Anexweapons_02-${{ github.ref_name }}'
          exclusions: '*.git* /*node_modules/* .editorconfig *.github* *.gradle* *.idea* *.run* /*build/* /*gradle/* /*libs /*readme_resources .gitattributes .gitignore build.gradle.kts gradle* gradle.* package.json package-lock.json README.md'
# generates list of all files in root directory, download log from actions tab in github to view
#      - name: check zip file log
#        run: |
#          cd
#          ls -R
# --------------------  Upload zip to Github Release --------------------
#      - name: Realease to Github Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: 'AnexWeapons.zip'
#          token: ${{ secrets.GITHUB_TOKEN }}
