name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-npm:
    runs-on: ubuntu-latest
#    node-version: '14'
    steps:
      - uses: actions/checkout@v2     # Checkout - https://github.com/actions/checkout -https://github.com/marketplace/actions/checkout
      - name: setup NodeJS
        uses: actions/setup-node@v2   # Setup Node.js environment - https://github.com/actions/setup-node - https://github.com/marketplace/actions/setup-node-js-environment
        with:
          node-version: '16'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run build --if-present
      - run: npm test
# --------------------  create zip file --------------------
  pack-zip:
    defaults:
      run:
        working-directory: AnexWeaponsArtifact
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    needs: build-npm
    steps:
      - uses: actions/checkout@v3
#        clean: 'false'        # if true checkout deletes everything after use and other jobs cannot access the files down the line
      - run: mkdir -p AnexWeaponsArtifact
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
#        directory: 'zip'
          filename: 'github-release-asset'
          exclusions: '*.git* /*node_modules/* .editorconfig'
#       *.git* *.github* *.gradle* *.idea* *.run* /*build/* /*gradle/* /*libs /*readme_resources .gitattributes .gitignore build.gradle.kts gradle* gradle.* package.json package-lock.json README.md
# generates list of all files in root directory, download log from actions tab in github to view
      - name: check zip file log
        run: |
          cd
          ls -R
# --------------------  move file to directory --------------------
      - uses: actions/upload-artifact@v3
        with:
          name: github-release-asset
          path: AnexWeaponsArtifact
      - name: Display structure of downloaded files
        run: ls -R
# --------------------  Upload zip to Github Release --------------------
      - name: Upload Asset zip to GitHub release
        uses: actions/download-artifact@v3
        with:
          name: github-release-asset
      - name: Display structure of downloaded files
        run: ls -R