name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
# --------------------  create zip folder --------------------
  creating-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v2
        with:
          name: testarchive
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
# --------------------  download artifact to working directory --------------------
  release-zip:
    name: "Release-zip"
    runs-on: ubuntu-latest
    needs: creating-zip
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v2
      - name: Display structure of downloaded files
        id: download-id
        run: ls -R
# -- display path of download  --
      - name: 'Echo download path'
        run: echo ${{steps.download-id.outputs.download-path}}

      - name: Emit a Github Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
#          title: "release-file"
          files: |
            "testarchive/*.zip"