name: Release manage
on: push
jobs:
  build-linux:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v2
      - name: Configure
        run: |
          sudo apt-get update
          sudo apt-get install  -y -f \
          libboost-all-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.0-37 \
          libwebkit2gtk-4.0-dev \
          libappindicator3-dev
      - name: Build
        run: bash build_linux.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux_binary
          path: bin/neutralino-linux_x64
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Boost
        run:  choco install boost-msvc-14.1
      - name: Build
        run: ./build_windows.bat
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: win_binary
          path: bin/neutralino-win_x64

  create-release-zip:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: clean previous binaries
        run:  |
          rm -f \
          ./bin/neutralino-linux_x64
          ./bin/neutralino-win_x64
      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux_binary
          path: ./bin/neutralino-linux_x64
      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: win_binary
          path: ./bin/neutralino-win_x64
      - name: Create Release zip
        uses: vimtor/actions-zip@v1
        with:
          files:  ./bin/neutralino-linux_x64 ./bin/neutralino-win_x64.exe
          dest: ./bin/neutralino-release.zip
      -name:  Add, Commit and Push Release
        uses: EndBug/add-and-commit@7.4.0
        with:
          default_author: github_actions
          message: 'add to zip'
          add:  './bin/neutralino-release.zip'