name: Release manage
on: push
jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
      - uses: actions/setup-node@v3.0.0
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          node-version: '14'
      - run: npm install
      - run: npm test