name: Build Next.js web application
on: push
jobs:
  release-project:
    name: Release source code
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: AnexWeapons_temp

      - name: Archive contents
        uses: thedoctor0/zip-release@master
        with:
          filename: AnexWeapons_archive.zip

      - name: Create GitHub Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Anex_SSH_Token }}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release V${{github.run_number}}

      - name: Upload Assets to GitHub Release
        uses: actions/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Anex_SSH_Token }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./AnexWeapons.zip
          asset_name: AnexWeapons_v${{github.run_number}}.zip
          asset_content_type: application/zip

  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: npm install
      - name: Build project assets
        run: npm run build
      - name: Upload assets artifacts to GitHub
        uses: actions/upload-artifact@v2.3.1
        with:
          name: AnexWeapons
          path: out/