name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
# --------------------  create zip folder --------------------
  creating-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v2
        with:
          name: testarchive
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
# --------------------  download artifact to working directory --------------------
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: testarchive
          asset_name: willthiswork-$tag
          tag: latest
          overwrite: true
          prerelease: false