name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  #  pull_request:
  #    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # --------------------  Prepare folder to be zipped --------------------
  pack-zip:
    name: Prepare Folder
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false    # without this checkout deletes empty folders after each use
          #{{ github.ref_name }}
      - run: mkdir Anexweapons
      - uses: actions/upload-artifact@v2
        with:
          name: AnexWeapons_temp
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
            !.git
            !.github
            !.gradle
            !.idea
            !.run
            !build
            !libs
            !readme_resources
#      - name: List all upload-artifact folders only
#        run: ls -R
#      - name: check upload-artifact file log
#        run: |
#          cd
#          ls -R
# --------------------  copy server folder to working folder --------------------
      - uses: actions/checkout@v3
        with:
          clean: false
      - uses: actions/download-artifact@v3
        id: download_id
        with:
          name: AnexWeapons_temp
          path: ${{ github.workspace }}/Anexweapons               # ${{ github.workspace }}/Anexweapons-${{ github.ref_name }}
      - name: 'Echo download path'
        run: echo ${{steps.download_id.outputs.download-path}}
      - name: check download-artifact file log
        run: |
          cd
          ls -R
# --------------------  create zip file --------------------
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Create Zip from Folders
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: "Anexweapons_ppp"
          path: ${{github.workspace}}/Anexweapons
          exclusions: '*data* *graphics* *jars* *sounds* *src* *.git* /*node_modules/* .editorconfig *.github* *.gradle* *.idea* *.run* /*build/* /*gradle/* /*libs /*readme_resources .gitattributes .gitignore build.gradle.kts gradle* gradle.* package.json package-lock.json README.md'
# generates list of all files in root directory, download log from actions tab in github to view
      - name: check thedoctor0 zip file log
        run: |
          cd
          ls -R
# --------------------  Upload zip to Github Release --------------------
      - uses: actions/checkout@v3
        with:
          clean: false
      - name: Realease to Github Releases
        uses: ncipollo/release-action@v1
        with:
          name: Anexweapons_fght-${{ github.ref_name }}
          artifacts: Anexweapons_ppp.zip
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: check ncipollo file log
        run: |
          cd
          ls -R
