name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
# --------------------  create zip folder --------------------
  creating-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        working-directory: .github/workflows/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        id: download-id
        with:
          name: testarchive
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
      - name: Display structure of downloaded files
        run: ls -R
#        working-directory: .github/workflows/
# -- display path of download  --
      - name: 'Echo download path'
        run: echo ${{steps.download-id.outputs.download-path}}
# --------------------  download artifact to working directory --------------------
      - uses: actions/checkout@v2
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: src/testarchive
          asset_name: willthiswork-$tag
          tag: latest
          overwrite: true
          prerelease: false