name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
# --------------------  create zip file --------------------
  pack-zip:
#    defaults:
#      run:
#        working-directory: .github/workflows/
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          clean: false    # if true checkout deletes everything after use and other jobs cannot access the files down the line
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
#          directory: '.github/workflows/'
          filename: 'github-release-asset'
          exclusions: '*.git* /*node_modules/* .editorconfig'
#       *.git* *.github* *.gradle* *.idea* *.run* /*build/* /*gradle/* /*libs /*readme_resources .gitattributes .gitignore build.gradle.kts gradle* gradle.* package.json package-lock.json README.md
# generates list of all files in root directory, download log from actions tab in github to view
      - name: check zip file log
        run: |
          cd
          ls -R
# --------------------  move file to directory --------------------
#      - uses: actions/upload-artifact@v3
#        with:
#          name: github-release-asset.zip
#          path: ./work/AnexWeapons/AnexWeapons
#      - name: Display structure of downloaded files
#        run: ls -R
# --------------------  Upload zip to Github Release --------------------
#      - name: Display structure of downloaded files
#        run: ls -R
#      - name: Upload Asset zip to GitHub release
#        uses: actions/download-artifact@v3
#        with:
#          name: github-release-asset
#          path: ${{ github.workspace }}/github-release-asset.zip
#      - name: Display structure of downloaded files
#        run: ls -R
# --------------------  Upload zip to Github Release --------------------
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'github-release-asset.zip'
          token: ${{ secrets.GITHUB_TOKEN }}