name: Release Manager
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
#  pull_request:
#    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
# --------------------  create zip file --------------------
  pack-zip:
    runs-on: ubuntu-latest
#    permissions:
#      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
#        directory: 'zip'
          filename: 'github-release-asset.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'
#       *.git* *.github* *.gradle* *.idea* *.run* /*build/* /*gradle/* /*libs /*readme_resources .gitattributes .gitignore build.gradle.kts gradle* gradle.* package.json package-lock.json README.md
      - name: Checkout
        uses: actions/checkout@v2
#    - name: Build
#      run: echo ${{ github.sha }} > release.zip
      - name: check zip file log
        run: |
          cd
          ls -R
# --------------------  create zip folder --------------------
  creating-zip:
    runs-on: ubuntu-latest
    needs: pack-zip
    permissions:
      contents: write
    defaults:
      run:
        working-directory: .github/workflows/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        id: download-id
        with:
          name: testarchive
          path: |
            data
            graphics
            jars
            sounds
            src
            Anex_Weapons.version
            mod_info.json
      - name: check directories zip log
        run: |
          cd
          ls -R
# --------------------  download artifact to working directory --------------------
  download-zip:
    runs-on: ubuntu-latest
    needs: creating-zip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        id: download-id
        with:
          name: testarchive
          path: .github/workflows/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .github/workflows/
      # -- display path of download  --
      - name: 'Echo download path'
        run: echo ${{steps.download-id.outputs.download-path}}
#
      - name: Display structure of downloaded files 1
        run: ls -R
      - name: Display structure of downloaded files 2
        run: ls
#      - name: check directories 1
#        run: |
#          cd .github/workflows/
#          ls -R
#      - name: check directories 2
#        run: |
#          cd .github/
#          ls -R
      - name: check directories 3
        run: |
          cd ..
          ls -R
      - name: check directories 4
        run: |
          cd
          ls -R
#        working-directory: .github/workflows/
# -- display path of download  --
      - name: 'Echo download path'
        run: echo ${{steps.download-id.outputs.download-path}}
# --------------------  download artifact to working directory --------------------
      - uses: actions/checkout@v2
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: .github/workflows/testarchive
          asset_name: willthiswork-$tag
          tag: latest
          overwrite: true
          prerelease: false